name: CI
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - '*'
jobs:
  run_application:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: ./gradlew clean build
